### ISSUE TITLE
Does startFrom have to be an absolute path?

### ISSUE THREAD

**Issue by StringKe** [imjuni/ctix#109]
I need to automatically create index.ts under the root of monorepo for the libs I create

repo: https://github.com/StringKe/ctix-monorepo-repo

```
{
  "spinnerStream": "stdout",
  "progressStream": "stdout",
  "reasonerStream": "stderr",
  "options": [
    {
      "mode": "create",
      "project": "./libs/canvas/tsconfig.json",
      "exportFilename": "index.ts",
      "useSemicolon": true,
      "useBanner": true,
      "useTimestamp": true,
      "quote": "'",
      "directive": "",
      "fileExt": "none",
      "overwrite": true,
      "backup": false,
      "generationStyle": "auto",
      "include": [
        "src/**/*.ts"
      ],
      "exclude": [
        "../../node_modules",
        "../../tmp"
      ],
      "skipEmptyDir": true,
      "startFrom": "./libs/canvas",
      "output": "./libs/canvas/src",
      "removeBackup": true,
      "forceYes": true
    }
  ]
}
```

**Comment by imjuni** [comment]
@StringKe Hi,

Thank you for your feedback so that `ctix` can be improved!

This issue was caused by a number of factors. In version `2.2.0` of `ctix`, when filtering files using the `include` and `exclude` options in monorepo, it was filtering files based on the directory where the script is executed and not filtering files correctly.

Another issue is in `tsconfig.json`. If you pass an empty array in the `include` and `file` fields, even if you composite other configuration files using it as a reference, the empty array is overwritten at the end, causing the TypeScript Compiler API to return a list of files as an empty array. 

1. Set the composite value to true in the `tsconfig.base.json` file
2. comment out or delete the files, include value in the `libs/canvas/src/lib/tsconfig.json` file
3. install `ctix` `2.3.0`
