### ISSUE TITLE
Disjoint paths sets on Windows

### ISSUE THREAD

**Issue by rplbc** [imjuni/ctix#114]
Hi,

is it possible that [this fragment](https://github.com/imjuni/ctix/blob/53ba535d8ce4216d4dfc0df966c2a7c284447fa7/src/modules/commands/creating.ts#L92) filters out every path on Windows? It seems like _IncludeContainer paths_ and _filePaths_ differ in separator (`\\`  and `/`).

**Comment by imjuni** [comment]
The `include` and `exclude` configurations can only accept `/` path seperators. This is because `glob` libraries such as `fast-glob` and `node-glob` do not recognize the `\\` character. Please enter the path with `/` characters. The glob package and the typescript compiler api will work fine in window if you enter the path with `/` characters. Please see to this [documentation](https://www.npmjs.com/package/fast-glob#how-to-write-patterns-on-windows)

**Comment by imjuni** [comment]
It seems that `node-glob` is searching for the file and returning it with a `\\` character in the `path`. The TypeScript compiler API will not be able to find the file because the windows environment also uses the `/` character as a path separator. Can you grab the [window-glob](https://github.com/imjuni/ctix/tree/feature/window-glob) branch and test it? I changed the node-glob package to return the `/` character instead of the `\\` character.

**Comment by rplbc** [comment]
It didn't work, I think `windowsPathsNoEscape` applies only to a pattern. I tried like this

```ts
const normalizeFilePath = (filePath: string) => filePath.replace(/\\/g, '/');

export function getGlobFiles<T extends GlobOptions>(glob: Glob<T>): string[] {
  ...
  return Array.from(filePathSet).map(normalizeFilePath);
}
```

and it worked. Removing this fragment from `isInclude` method also worked

```ts
if (path.isAbsolute(filePath)) {
  return this.#map.get(filePath) != null;
}
```

But then there is an issue

```ts
export * from './comments\getCommentKind';
export * from './comments\getCommentWorkspace';
...
```

which I believe is because of `addCurrentDirPrefix`

**Comment by imjuni** [comment]
The TypeScript import statement has to use the posix path seperator. The `addCurrentDirPrefix` works fine, but the other functions that generate the import path need to be fixed.

I don't have time to work on this right now for some personal reasons. PRs are always welcome. However, it will be a while before I get around to fixing this.

**Comment by Vulthil** [comment]
I'm facing a similar issue, so I'm just gonna chime in.

When trying to use 'create' mode, nothing is generated on a windows machine.

If I open the same folder in WSL (Windows Subsystem for Linux) and run the same command, the output is correctly generated.

**Comment by imjuni** [comment]
@rplbc @Vulthil Thank you for feedback.

`2.4.0` version has been released. `2.4.0` version supports the windows environment, and I've tested it in other packages I've developed and it works fine in the windows environment. Thank you for your patience during this long wait.
